version: 2
jobs:
  build:
    context: Prod
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo $CREDENTIALS.
      - run:
          name: Print the Current Time
          command: date
